language: php

env:
  global:
    - GLPI_SOURCE="https://github.com/glpi-project/glpi -b 9.2/bugfixes" 
    - PHPUNIT_ARGS="--verbose --debug"
    - DB="glpi-test"
    - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/slimerjs:$PATH

addons:
  firefox: "latest-esr"

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  
before_script:
  - phpenv config-rm xdebug.ini || true
  - mysql -u root -e 'create database $DB;'
  - git clone $GLPI_SOURCE --depth 1 ../glpi && cd ../glpi
  - mv ../formcreator plugins/formcreator
  - composer install --no-dev
  - php tools/cliinstall.php --db=$DB --user=root --tests --lang=en_US
  - cd plugins/formcreator
  - rm composer.lock
  - composer install
  - npm install -g phantomjs-prebuilt
  - npm install -g casperjs
  - npm install -g slimerjs
  - php -S localhost:8088 --docroot ../.. ../../tests/router.php &>/dev/null &
  - mysql --version
  - casperjs --version

script:
  - vendor/bin/phpunit $PHPUNIT_ARGS --testsuite Install
  - vendor/bin/phpunit $PHPUNIT_ARGS --testsuite Unit
  - vendor/bin/phpunit $PHPUNIT_ARGS --testsuite Integration
  - mysql -u root $DB < save.sql
  - casperjs test tests/0020_Functional/*Test.js --engine=phantomjs
  - mysql -u root $DB < save.sql
  - casperjs test tests/0020_Functional/*Test.js --engine=slimerjs
  - vendor/bin/phpunit $PHPUNIT_ARGS --testsuite Uninstall
  - if [[ "$CS" == "true" ]]; then vendor/bin/robo --no-interaction code:cs; fi

matrix:
  include:
    - php: '5.6'
    - php: '7.0'
    - php: '7.1'
    - php: '7.2'
      env: CS=true
    - php: nightly
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
