language: php

env:
  global:
    - GLPI_SOURCE="https://github.com/glpi-project/glpi"
    - CS=7.2
    - DBUSER=root
    - DBNAME=glpitest
    - OLDDBNAME=glpiupgradetest
    - AFTER_SUCCESS_BRANCH=9.4/bugfixes
  matrix:
    - GLPI_BRANCH=9.4/bugfixes
    - GLPI_BRANCH=master

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly
#    - env: GLPI_BRANCH=master

before_script:
  - "./tests/before_script.sh"

script:
  - COVERAGE="-ncc"
  - if [ "${TRAVIS_PHP_VERSION:0:3}" = "$CS" ] && [ "$GLPI_BRANCH" = "$AFTER_SUCCESS_BRANCH" ]; then COVERAGE="--nccfc CommonTreeDropdown CommonDropdown CommonDBTM CommonGLPI CommonDBChild CommonDBConnexity CommonDBRelation"; fi
  - if [ -e ../../scripts/cliinstall.php ] ; then php ../../scripts/cliinstall.php --db=$OLDDBNAME --user=root --tests ; fi
  - if [ -e ../../bin/console ] ; then php ../../bin/console glpi:database:install --db-name=$OLDDBNAME --db-user=root --config-dir=../../tests --no-interaction --force; fi
  - mysql -u root $OLDDBNAME < tests/plugin_formcreator_empty_2.5.0.sql
  - mysql -u root $OLDDBNAME < tests/plugin_formcreator_config_2.5.0.sql
  - php scripts/cliinstall.php --tests
  - rm ../../tests/config_db.php
  - if [ -e ../../scripts/cliinstall.php ] ; then php ../../scripts/cliinstall.php --db=$DBNAME --user=root --tests ; fi
  - if [ -e ../../bin/console ] ; then php ../../bin/console glpi:database:install --db-name=$DBNAME --db-user=root --config-dir=../../tests --no-interaction --force; fi
  - vendor/bin/atoum -ft -bf tests/bootstrap.php -d tests/suite-install -ncc
  - vendor/bin/atoum -ft -bf tests/bootstrap.php -d tests/suite-integration $COVERAGE
  - vendor/bin/atoum -ft -bf tests/bootstrap.php -d tests/suite-unit $COVERAGE
  - vendor/bin/atoum -ft -bf tests/bootstrap.php -d tests/suite-uninstall -ncc
  - if [ ${TRAVIS_PHP_VERSION:0:3} == "$CS" ] && [ "$GLPI_BRANCH" = "$AFTER_SUCCESS_BRANCH" ]; then vendor/bin/robo --no-interaction code:cs; fi

after_success:
  # let's update the documentation and locales
  - if [ ${TRAVIS_PHP_VERSION:0:3} == "$CS" ] && [ "$GLPI_BRANCH" = "$AFTER_SUCCESS_BRANCH" ]; then tests/after_success.sh; fi
  - if [ ${TRAVIS_PHP_VERSION:0:3} == "$APIDOCS_PHP" ] && [ "$GLPI_BRANCH" = "$AFTER_SUCCESS_BRANCH" ]; then tests/apidocs.sh; fi

cache:
  directories:
    - $HOME/.composer/cache
