language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly

before_script:
  - git clone https://github.com/glpi-project/glpi --depth 1 -b 9.1.2 ../glpi && cd ../glpi
  - mv ../formcreator plugins/formcreator
  - composer install --no-dev
  - php tools/cliinstall.php --db=glpi-test --user=travis --tests
  - cd plugins/formcreator
  - rm composer.lock
  - composer install

script:
  - vendor/bin/phpunit --verbose
  - vendor/bin/robo --no-interaction code:cs

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
